ALTER TABLE Student ADD CONSTRAINT PRIMARY KEY (id);
ALTER TABLE Professor ADD CONSTRAINT PRIMARY KEY (id);
ALTER TABLE Course ADD CONSTRAINT PRIMARY KEY (crsCode);

ALTER TABLE Teaching MODIFY profId INT NOT NULL;
ALTER TABLE Teaching MODIFY crsCode VARCHAR(255) NOT NULL;
ALTER TABLE Teaching MODIFY semester VARCHAR(255) NOT NULL;

ALTER TABLE Transcript MODIFY studId INT NOT NULL;
ALTER TABLE Transcript MODIFY crsCode VARCHAR(255) NOT NULL;
ALTER TABLE Transcript MODIFY semester VARCHAR(255) NOT NULL;
